steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/light-bringer/simple-crud-rest-api.git']  
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['start']
timeout: "1600s"